#!/usr/bin/env bash
# Entrypoint for the Jumpcoin Qt wallet container.
# Runs as root so it can prep system dirs, then hands off to supervisord
# which drops to the unprivileged `jumpcoin` user.

set -euo pipefail

DATA_DIR="/home/jumpcoin/.jumpcoin"
CONF_FILE="${DATA_DIR}/jumpcoin.conf"
VNC_PASSWD_FILE="/home/jumpcoin/.vnc/passwd"
SUPERVISORD_CONF="/etc/supervisor/supervisord.conf"

log() { printf '[entrypoint] %s\n' "$*"; }

# -----------------------------------------------------------------------
# 1. Make runtime dirs writable for the unprivileged user
# -----------------------------------------------------------------------
mkdir -p /home/jumpcoin/.supervisor /home/jumpcoin/Desktop
# Skip read-only bind mounts (e.g. user-supplied peers.dat) when
# fixing ownership; chown on a :ro file would fail and abort the script.
chown -R jumpcoin:jumpcoin /home/jumpcoin 2>/dev/null \
    || find /home/jumpcoin -xdev -writable -exec chown jumpcoin:jumpcoin {} +

# Desktop shortcut so the user can re-launch the wallet if it ever
# crashes (supervisord restarts it automatically, but the user may not
# want to wait for the autorestart delay).
cat > /home/jumpcoin/Desktop/jumpcoin-qt.desktop <<'EOF'
[Desktop Entry]
Type=Application
Name=Jumpcoin-Qt
Comment=Start or restart the Jumpcoin Qt wallet
Exec=/usr/local/bin/launch-jumpcoin-qt
Icon=bitcoin
Terminal=false
Categories=Office;Finance;Network;
EOF
chmod +x /home/jumpcoin/Desktop/jumpcoin-qt.desktop
chown jumpcoin:jumpcoin /home/jumpcoin/Desktop/jumpcoin-qt.desktop

# Also try to fix /var/run and /var/log/supervisor ownership - this
# works in most cases but may fail on some host kernels (harmless)
chown -R jumpcoin:jumpcoin /var/run /var/log/supervisor /var/lock 2>/dev/null || true

# -----------------------------------------------------------------------
# 2. jumpcoin.conf  (only generated if it doesn't already exist)
# -----------------------------------------------------------------------
if [[ "${RPC_USER:-}" == "jumpcoin" && "${RPC_PASSWORD:-}" == "jumpcoin" ]]; then
    log "WARNING: default RPC credentials in use (jumpcoin/jumpcoin) — set RPC_USER and RPC_PASSWORD before exposing port ${RPC_PORT:-31240}"
fi

if [[ ! -s "${CONF_FILE}" ]]; then
    log "Generating ${CONF_FILE}"
    cat > "${CONF_FILE}" <<EOF
# Generated by jumpcoin docker entrypoint
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASSWORD}
rpcallowip=${WALLET_RPCALLOWIP}
rpcport=${RPC_PORT}
listen=1
port=${P2P_PORT}
daemon=0
server=1
fallbackfee=0.0002
EOF
    chown jumpcoin:jumpcoin "${CONF_FILE}"
else
    # Existing config: make sure the wallet is enabled (jumpcoin-qt is
    # the only process inside the container, so it MUST own the
    # wallet, otherwise the Send/Receive/Staking tabs disappear).
    if grep -q '^[[:space:]]*disablewallet=1' "${CONF_FILE}"; then
        log "Re-enabling wallet in existing ${CONF_FILE}"
        sed -i 's/^[[:space:]]*disablewallet=1/# disablewallet=1 (was: 1, now enabled)/' "${CONF_FILE}"
        chown jumpcoin:jumpcoin "${CONF_FILE}"
    fi
fi

# Auto-configure Tor proxy for the :tor image variant.
# If /usr/bin/tor is present but the user hasn't set a proxy or noonion
# override via DAEMON_ARGS, add proxy=127.0.0.1:9050 (clearnet+onion).
if [[ -x /usr/bin/tor ]]; then
    _tor_override=false
    for _arg in ${DAEMON_ARGS:-}; do
        case "${_arg#-}" in proxy=*|noonion*) _tor_override=true; break ;; esac
    done
    if [[ "${_tor_override}" == "false" ]] && ! grep -q '^proxy=' "${CONF_FILE}" 2>/dev/null; then
        log "Tor variant detected: adding proxy=127.0.0.1:9050 (clearnet+onion). Use DAEMON_ARGS=-onlynet=onion for onion-only, or -noonion to disable."
        printf '\nproxy=127.0.0.1:9050\n' >> "${CONF_FILE}"
        chown jumpcoin:jumpcoin "${CONF_FILE}"
    fi
fi

# Clean up stale wallet lock from a previous (unclean) shutdown
LOCK_FILE="${DATA_DIR}/.lock"
if [[ -f "${LOCK_FILE}" ]]; then
    log "Removing stale wallet lock: ${LOCK_FILE}"
    rm -f "${LOCK_FILE}"
fi

if [[ -n "${DAEMON_ARGS}" ]]; then
    # Idempotent: only append once so repeated restarts don't grow the file.
    # DAEMON_ARGS changes take effect after a full data-dir reset.
    if ! grep -q '^# User-supplied args:' "${CONF_FILE}"; then
        log "Appending DAEMON_ARGS to ${CONF_FILE}"
        printf '\n# User-supplied args:\n' >> "${CONF_FILE}"
        # Strip leading dashes (conf format is key=value, not -key=value)
        # and write one option per line so each is parsed independently.
        for arg in ${DAEMON_ARGS}; do
            arg="${arg#--}"
            arg="${arg#-}"
            printf '%s\n' "${arg}" >> "${CONF_FILE}"
        done
        chown jumpcoin:jumpcoin "${CONF_FILE}"
    else
        log "WARNING: DAEMON_ARGS already applied to ${CONF_FILE} — changes are ignored until the data dir is reset"
    fi
fi

# -----------------------------------------------------------------------
# 3. VNC password (the .vnc dir must be writable by jumpcoin)
# -----------------------------------------------------------------------
mkdir -p "$(dirname "${VNC_PASSWD_FILE}")"
chown -R jumpcoin:jumpcoin "$(dirname "${VNC_PASSWD_FILE}")"
# Remove stale lock/pid files from a previous container run
find "$(dirname "${VNC_PASSWD_FILE}")" -maxdepth 1 \( -name '*.pid' -o -name '*.log' \) -delete 2>/dev/null || true
if [[ ! -f "${VNC_PASSWD_FILE}" ]] || [[ ! -s "${VNC_PASSWD_FILE}" ]]; then
    if [[ -n "${VNC_PASSWORD:-}" ]]; then
        log "Setting VNC password"
        printf '%s\n%s\n' "${VNC_PASSWORD}" "${VNC_PASSWORD}" \
            | vncpasswd -f > "${VNC_PASSWD_FILE}"
    else
        log "No VNC_PASSWORD set - VNC runs without authentication (SecurityTypes=None)"
        # When no password is set we need to switch to SecurityTypes=None,
        # otherwise VncAuth will reject every client.
        export VNC_SECURITY_TYPES="None"
        : > "${VNC_PASSWD_FILE}"
    fi
    chmod 600 "${VNC_PASSWD_FILE}"
    chown jumpcoin:jumpcoin "${VNC_PASSWD_FILE}"
fi

# TigerVNC requires an explicit opt-in to run without authentication
if [[ "${VNC_SECURITY_TYPES:-}" == "None" ]]; then
    export VNC_INSECURE_OK="--I-KNOW-THIS-IS-INSECURE"
else
    export VNC_INSECURE_OK=""
fi

# -----------------------------------------------------------------------
# 4. Hand off to supervisord (which will drop to jumpcoin via `user=jumpcoin`)
# -----------------------------------------------------------------------

# In the :latest image the debian-tor user does not exist (tor is not
# installed).  Supervisord validates user= at startup and aborts if the
# user is missing, even when the program block is a no-op.  Patch the
# conf in-place so both variants share one file.
if ! id debian-tor >/dev/null 2>&1; then
    sed -i 's/^user=debian-tor$/user=root/' "${SUPERVISORD_CONF}"
fi

log "Starting supervisord"
exec supervisord -c "${SUPERVISORD_CONF}" -n
