#!/usr/bin/env bash
# Entrypoint for the Jumpcoin Qt wallet container.
# Runs as root so it can prep system dirs, then hands off to supervisord
# which drops to the unprivileged `jumpcoin` user.

set -euo pipefail

DATA_DIR="/home/jumpcoin/.jumpcoin"
CONF_FILE="${DATA_DIR}/jumpcoin.conf"
VNC_PASSWD_FILE="/home/jumpcoin/.vnc/passwd"
SUPERVISORD_CONF="/etc/supervisor/supervisord.conf"

log() { printf '[entrypoint] %s\n' "$*"; }

# -----------------------------------------------------------------------
# 1. Make runtime dirs writable for the unprivileged user
# -----------------------------------------------------------------------
mkdir -p /home/jumpcoin/.supervisor
# Skip read-only bind mounts (e.g. user-supplied peers.dat) when
# fixing ownership; chown on a :ro file would fail and abort the script.
chown -R jumpcoin:jumpcoin /home/jumpcoin 2>/dev/null \
    || find /home/jumpcoin -xdev -writable -exec chown jumpcoin:jumpcoin {} +

# Also try to fix /var/run and /var/log/supervisor ownership - this
# works in most cases but may fail on some host kernels (harmless)
chown -R jumpcoin:jumpcoin /var/run /var/log/supervisor /var/lock 2>/dev/null || true

# -----------------------------------------------------------------------
# 2. jumpcoin.conf  (only generated if it doesn't already exist)
# -----------------------------------------------------------------------
if [[ ! -s "${CONF_FILE}" ]]; then
    log "Generating ${CONF_FILE}"
    cat > "${CONF_FILE}" <<EOF
# Generated by jumpcoin docker entrypoint
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASSWORD}
rpcallowip=${WALLET_RPCALLOWIP}
rpcport=${RPC_PORT}
listen=1
port=${P2P_PORT}
daemon=0
server=1
fallbackfee=0.0002
EOF
    chown jumpcoin:jumpcoin "${CONF_FILE}"
else
    # Existing config: make sure the wallet is enabled (jumpcoin-qt is
    # the only process inside the container, so it MUST own the
    # wallet, otherwise the Send/Receive/Staking tabs disappear).
    if grep -q '^[[:space:]]*disablewallet=1' "${CONF_FILE}"; then
        log "Re-enabling wallet in existing ${CONF_FILE}"
        sed -i 's/^[[:space:]]*disablewallet=1/# disablewallet=1 (was: 1, now enabled)/' "${CONF_FILE}"
        chown jumpcoin:jumpcoin "${CONF_FILE}"
    fi
fi

# Clean up stale wallet lock from a previous (unclean) shutdown
LOCK_FILE="${DATA_DIR}/.lock"
if [[ -f "${LOCK_FILE}" ]]; then
    log "Removing stale wallet lock: ${LOCK_FILE}"
    rm -f "${LOCK_FILE}"
fi

if [[ -n "${DAEMON_ARGS}" ]]; then
    printf '\n# User-supplied args:\n%s\n' "${DAEMON_ARGS}" >> "${CONF_FILE}"
fi

# -----------------------------------------------------------------------
# 3. VNC password (the .vnc dir must be writable by jumpcoin)
# -----------------------------------------------------------------------
mkdir -p "$(dirname "${VNC_PASSWD_FILE}")"
chown -R jumpcoin:jumpcoin "$(dirname "${VNC_PASSWD_FILE}")"
# Remove stale lock/pid files from a previous container run
find "$(dirname "${VNC_PASSWD_FILE}")" -maxdepth 1 \( -name '*.pid' -o -name '*.log' \) -delete 2>/dev/null || true
if [[ ! -f "${VNC_PASSWD_FILE}" ]] || [[ ! -s "${VNC_PASSWD_FILE}" ]]; then
    if [[ -n "${VNC_PASSWORD:-}" ]]; then
        log "Setting VNC password"
        printf '%s\n%s\n' "${VNC_PASSWORD}" "${VNC_PASSWORD}" \
            | vncpasswd -f > "${VNC_PASSWD_FILE}"
    else
        log "No VNC_PASSWORD set - VNC runs without authentication (SecurityTypes=None)"
        # When no password is set we need to switch to SecurityTypes=None,
        # otherwise VncAuth will reject every client.
        export VNC_SECURITY_TYPES="None"
        : > "${VNC_PASSWD_FILE}"
    fi
    chmod 600 "${VNC_PASSWD_FILE}"
    chown jumpcoin:jumpcoin "${VNC_PASSWD_FILE}"
fi

# TigerVNC requires an explicit opt-in to run without authentication
if [[ "${VNC_SECURITY_TYPES:-}" == "None" ]]; then
    export VNC_INSECURE_OK="--I-KNOW-THIS-IS-INSECURE"
else
    export VNC_INSECURE_OK=""
fi

# -----------------------------------------------------------------------
# 4. Hand off to supervisord (which will drop to jumpcoin via `user=jumpcoin`)
# -----------------------------------------------------------------------
log "Starting supervisord"
exec supervisord -c "${SUPERVISORD_CONF}" -n
